
services:
  brandgpt-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app                              # your FastAPI code
      - ./llama.cpp/build/bin/llama-cli:/app/llama.cpp/build/bin/llama-cli
      - ./models:/app/models                       # Mistral GGUF weights
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app

    gpus: all
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - brandgpt-app
    environment:
      - HOST=0.0.0.0
      - NODE_OPTIONS=--dns-result-order=ipv4first

volumes:
  frontend_node_modules:
